# Generated by Django 4.2.6 on 2023-11-03 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaruselLanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('order', models.SmallIntegerField(default=0, verbose_name='Orden')),
                ('image', models.ImageField(upload_to='Carrusel', verbose_name='Imagen')),
                ('image_title', models.ImageField(upload_to='Carrusel', verbose_name='Imagen de titulo')),
                ('width', models.CharField(max_length=20, verbose_name='Ancho')),
                ('height', models.CharField(max_length=20, verbose_name='Alto')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Imagen del carrusel',
                'verbose_name_plural': 'Imagenes del carrusel',
                'ordering': ['order', 'title'],
            },
        ),
    ]
