# Generated by Django 4.2.6 on 2023-11-03 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('mail', models.EmailField(max_length=200, verbose_name='Correo electrónico')),
                ('phone', models.CharField(max_length=200, verbose_name='Número de teléfono')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('status', models.BooleanField(default=False, verbose_name='Contestado')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
                'ordering': ['-created'],
            },
        ),
    ]
